### ISSUE TITLE
Sortable not works

### ISSUE THREAD

**Issue by juanmendez92** [RoXuS/paper-datatable-api#1]
Hi, I have this code

```
    <iron-ajax
      id="ajax"
      auto
      method="GET"
      url="[[imagesRoute]]"
      handle-as="json"
      last-response="{{images}}"></iron-ajax>

    <paper-datatable-api id="table" data="[[images]]" selectable-data-key="file_name" on-sort="_handleSort">
      <paper-datatable-api-column header="Nombre" property="file_name" hideable sortable>
        <template>
          <span>{{value}}</span>
        </template>
      </paper-datatable-api-column>
      <paper-datatable-api-column header="" property="file_path">
        <template>
          <img height="30px" src="{{value}}" alt="" />
        </template>
      </paper-datatable-api-column>
      <paper-datatable-api-column header="Tamaño" hideable property="file_size">
        <template>
          <span>{{value}} bytes</span>
        </template>
      </paper-datatable-api-column>
      <paper-datatable-api-column header="Acciones" property="file_uuid">
        <template>
          <paper-button raised on-tap="_test">Eliminar</paper-button>
        </template>
      </paper-datatable-api-column>
    </paper-datatable-api>
```

But when I check the page, the sort doesn't works. I'm doing something wrong?

Another thing, the toggleColumn method only works with the first two columns, no with the columns with hideable attribute.

**Comment by RoXuS** [comment]
hello @juanmendez92,

The sort works with an API like springs data rest or other, it does not do the sort !

Your function `_handleSort` get an event object with the following parameters : `{ sort: { property: string, direction: 'asc'|'desc' }, column: object }`.
You have to call your API with the sort parameters and do the job backend side, for example `url=[[imagesRoute]]&sort=acciones,asc`.

You can see the demo => https://github.com/RoXuS/paper-datatable-api/blob/master/demo/advanced-demo.html

My function `_handleSort` set the sort parameters in a `sortProperty` :

```
      _handleSort: function(event) {
        this.sortProperty = event.detail.sort.property + ',' + event.detail.sort.direction;
      }
```

And the `sortProperty` is used in `iron-ajax` url :  

```
    <iron-ajax
      auto
      url="data/data-page=[[page]]&size=[[size]]&sort=[[sortProperty]].json"
      on-response="_handleResponse">
```

See https://github.com/RoXuS/paper-datatable-api/blob/master/demo/api-sample.html component.

Doesn't hesitate to tell me if I am not clear.

**Comment by juanmendez92** [comment]
Perfect, I understand now. Another thing, in the same code I'm trying to hide two columns, the first and the third, but only the first column is hidden. If I use the toggleColumn method and pass as parameter 0, the first column change, but if I pass as parameter 2 (the position of the another column to toggle) it doesn't change the column.

**Comment by RoXuS** [comment]
@juanmendez92 ohh yes it was a bug, I have fixed on master branch (see https://github.com/RoXuS/paper-datatable-api/commit/9010a068c90b55ce02379096bf1d03371aef4e3a), can you test to tell me if it is ok then I will add some tests and I will do a 0.0.7.

**Comment by juanmendez92** [comment]
It works, the columns are changing now. Thanks!

**Comment by RoXuS** [comment]
I have tagged the 0.0.7 with the fix, thx.
