### ISSUE TITLE
Show attribute default value

### ISSUE THREAD

**Issue by H3dz** [RoXuS/paper-datatable-api#10]
It would be nice to be able to hide a column by default.

Currently, the show attribute is set to true which makes it impossible to hide a column by default.
See https://www.polymer-project.org/1.0/docs/devguide/properties#configuring-boolean-properties

One solution would be to rename the attribute to hidden, default false, and update the code accordingly.

Additionally, a public method to show/hide a column programmatically would be useful (at least in my case). I created a method in my element similar to the toggleColumn method.

```
        _setColumnVisibility: function (columnPosition, show) {
          var paperDatatable = this.$$('paper-datatable-api');
          var column = paperDatatable._columns[columnPosition];
          if (column && column.hideable) {
            if (show == column.show) {
                return;
            }
            var indexColumn = paperDatatable.selectable ? columnPosition + 2 : columnPosition + 1;
            var cssQuery = 'tr th:nth-of-type(' + indexColumn +
              '), tr td:nth-of-type(' + indexColumn + ')';
              Polymer.dom(paperDatatable.root).querySelectorAll(cssQuery).forEach(function (tdTh) {
                tdTh.style.display = (!show ? 'none' : 'table-cell');
              }, paperDatatable);

            column.show = false;
            var toggleColumnIndex = paperDatatable.toggleColumns.findIndex(function (toggleColumn) {
                return toggleColumn.position === columnPosition;
              });

            paperDatatable.set('toggleColumns.' + toggleColumnIndex + '.show', show);
            paperDatatable._resizeHeader();
          }
        }
```

Thanks

**Comment by RoXuS** [comment]
Hello !

Currently we hide column by default in our element by using this:

```
    if (!this.alreadyHidden) {
      this.$$('paper-datatable-api').toggleColumn(5);
      this.$$('paper-datatable-api').toggleColumn(6);
      this.alreadyHidden = true;
    }
```

(When we load data in the table).

[I have added an example here](https://github.com/RoXuS/paper-datatable-api/commit/0cae0c6f9f5e2f7fdf8127e7acddb71fe96cb1be).

Indeed, add a dedicated attribute to it would be cleaner ... I'll try to do if I have enough time, if you can do it, I accept your PR with pleasure.

**Comment by H3dz** [comment]
Hi,

Thanks for the example, that's certainly a better way to do it.

I'll try to contribute to the project when I have time.

Thanks
