### ISSUE TITLE
colspan equivalent

### ISSUE THREAD

**Issue by bennypowers** [RoXuS/paper-datatable-api#16]
I would like to set up complex tables such as
<table>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>
  <tr>
    <td colspan="2">expanded</td>
    <td colspan="2">expanded</td>
    <td colspan="2">expanded</td>
  </tr>
  <tr>
    <td colspan="3">foo</td>
    <td colspan="3">bar</td>
  </tr>
  <tr>
    <td>short</td>
    <td colspan="6">expanded*3</td>
  </tr>
</table>

Can I do that with paper-datatable-api?

**Comment by RoXuS** [comment]
Hello @bennypowers,

No you can't ...

**Comment by RoXuS** [comment]
I close this issue, if you have others questions, don't hesitate open a new issue.

Thx.
