### ISSUE TITLE
Data is not being displayed in the Grid/Datatable

### ISSUE THREAD

**Issue by atifwaqar** [RoXuS/paper-datatable-api#17]
Hi, 
I am new to polymer, so if this is a newbie question please dont mind. 
I am getting data in my Json after the html is loaded, I debugged your code a little bit to confirm these 2 cases : 
1. If the data is already loaded, and then the html is loaded, things work fine
2. If the html is successfully loaded, and `Ready()` function in your code is ran **before data is loaded**, nothing is displayed.

I am using PuppetJS and my case is the 2nd one, So is there a way to somehow bind my JSON data, so that whenever it is loaded or changed, it reflects the change in the Grid/Datatable?

**Comment by RoXuS** [comment]
Hello @atifwaqar,

The 2 cases work, the `paper-datatable-api` observer the data, it renders the view when the `_dataChanged` function is called. (`_dataChanged` is called when the data change).

So you just have to wait the HTML and when the HTML is ready set the data array with your JSON array.

**Comment by atifwaqar** [comment]
@RoXuS I just debugged, my and the control enters in `_dataChanged` function only once. And then i set the data array with my Json, and nothing happens, the control does not even enter in `_dataChanged` function

**Comment by RoXuS** [comment]
how you set data in `paper-datatable-api` ?

**Comment by atifwaqar** [comment]
here my html code for it : 

```
<paper-datatable-api data="{{model.WebPublicationIdentifiers}}" selectable multi-selection>
    <paper-datatable-api-column header="ObId" property="Regex$" sortable editable>
        <template>
            <span>{{value}}</span>
        </template>
    </paper-datatable-api-column>
</paper-datatable-api>
```

Where as `model.WebPublicationIdentifiers` is a Json as following :
```
  "WebPublicationIdentifiers": [
    {
      "ObId": "",
      "Host": "",
      "Regex$": ""
    }
  ],
```

and `{{model.WebPublicationIdentifiers}}` is a puppetJS variable.

**Comment by RoXuS** [comment]
try to set "manually" the data, for example:
```javascript
// When your code is ready
this.$$('paper-datatable-api').data = model.WebPublicationIdentifiers
```

**Comment by atifwaqar** [comment]
Still not working. 
after adding your suggested line of code, i debugged the browser and this is what i see : 
![image](https://cloud.githubusercontent.com/assets/4388707/20893257/6989076a-bb11-11e6-82b4-11b8e36b2876.png)

So the data is in there, But the grid is still not displaying the data. Then I removed the suggested line of code and debugged again, and the result was same as shown in above picture.

**Comment by RoXuS** [comment]
When dataChanged is fired, what is the value of data ?

```javascript
// Here
  _dataChanged(data) {
    this.async(() => {
      this._removeRows();
      this._fillRows(data);
      this._fillColumns();
      this._resizeHeader();
      this._footerPositionChange(this.footerPosition);
    });
  }
```

**Comment by atifwaqar** [comment]
I put a debugger in your code and Refreshed the page. `_dataChanged` function is fired twice. first time when the page is loaded but data is not loaded, 
![image](https://cloud.githubusercontent.com/assets/4388707/20893602/a544acf4-bb12-11e6-90bb-a58bd96f633a.png)

and 2nd time when the data is loaded. 
![image](https://cloud.githubusercontent.com/assets/4388707/20893565/87c35590-bb12-11e6-944b-929dc08238bc.png)

**Comment by RoXuS** [comment]
The data variable seems to be undefined right ? (second screen line 397)

**Comment by atifwaqar** [comment]
A strange thing i just noticed. 
For case 1 when I hover my mouse on `data`, it shows my array : 
![image](https://cloud.githubusercontent.com/assets/4388707/20893858/8c10bfce-bb13-11e6-87fe-af8d5f444b07.png)

For case 2 when I hover my mouse on `data` It shows `undefnied` : 
![image](https://cloud.githubusercontent.com/assets/4388707/20893930/db7e9702-bb13-11e6-96e7-16659b1b5435.png)

**Comment by atifwaqar** [comment]
@RoXuS Yes you are right. So how do I solve this?

**Comment by RoXuS** [comment]
I don't know, it should be ok...

Try with a simple iron-ajax to see if you have the issue:
```
<link rel="import" href="bower_components/paper-datatable-api/dist/paper-datatable-api-column.html">
<link rel="import" href="bower_components/paper-datatable-api/dist/paper-datatable-api.html">

<iron-ajax auto url="data.json" last-response="{{data}}"></iron-ajax>

<paper-datatable-api data="[[data]]">
  <paper-datatable-api-column header="Fruit" property="fruit">
    <template>
      <span>{{value}}</span>
    </template>
  </paper-datatable-api-column>
  <paper-datatable-api-column header="Color" property="color">
    <template>
      <span>{{value}}</span>
    </template>
  </paper-datatable-api-column>
</paper-datatable-api>
```

**Comment by atifwaqar** [comment]
using this code i get an error in Chrome Console `http://localhost:8080/sc/data.json 404 (Not Found)` 
What am I suppose to write in the `url` field in this code : 
`<iron-ajax auto url="data.json" last-response="{{model.WebPublicationIdentifiers}}"></iron-ajax>`

**Comment by RoXuS** [comment]
no you have to create a simple `data.json` in the root of your server with your data, then `iron-ajax` set the {{data}}.

**Comment by atifwaqar** [comment]
Well, this works, but it only populates data from the json `data.json`. And this can not work in live environment.

**Comment by RoXuS** [comment]
Of course, it was a test to know what is not work.

How to get your data from puppetjs ?

**Comment by atifwaqar** [comment]
Ah ok. Well the test succeeded :)
and sorry i couldnt understand your point about getting data from puppetjs?
do you want a sample data like this : 
```
        "WebPublicationIdentifiers": [
          {
            "ObId": "BNR",
            "Host": "",
            "Regex$": "krogsveen\\.no/Kjoepe-bolig/.*?-(\\d{5}\\d*)"
          },
          {
            "ObId": "BuU",
            "Host": "",
            "Regex$": "asdf"
          },
          {
            "ObId": "Bul",
            "Host": "",
            "Regex$": "asdfasdf"
          }
        ],
```

**Comment by RoXuS** [comment]
ok where `WebPublicationIdentifiers` is declared ?

**Comment by atifwaqar** [comment]
Its in a Json. 
I am using `Starcounter` platform. Which uses PuppetJs to fetch/store data using Json files.
and this is how the code looks like in the Json File : 
```
{
  "$WebPublicationIdentifiers": { "Bind": "WebPublicationIdentifiers_" },
  "WebPublicationIdentifiers": [
    {
      "ObId": "",
      "Host": "",
      "Regex$": ""
    }
  ]
}
```

**Comment by RoXuS** [comment]
Sorry, I do not really understand how your code is structured, I think you can't use data in the HTML, you have to set the data from your javascript.

For example you can add something like this (where you data is available):
```javascript
console.log(model.WebPublicationIdentifiers);
this.$$('paper-datatable-api').data = model.WebPublicationIdentifiers;
console.log(this.$$('paper-datatable-api').data);
```
Then see me the output in your console.

**Comment by atifwaqar** [comment]
When I write only this code, things look good in debugger :
![image](https://cloud.githubusercontent.com/assets/4388707/20895586/4b0a2d56-bb1a-11e6-9172-884004339aec.png)

But first thing, the code did not enter in `_dataChanged` and second thing data did not appear on the page

**Comment by atifwaqar** [comment]
and when I use the code `this.$$('paper-datatable-api')._dataChanged();` in my script along with `this.$$('paper-datatable-api').data = this.model.WebPublicationIdentifiers;`, the data gets undefined

**Comment by atifwaqar** [comment]
Here is the output you asked for : 
![image](https://cloud.githubusercontent.com/assets/4388707/20895821/41021fca-bb1b-11e6-9d2f-b093ef1c6992.png)

**Comment by RoXuS** [comment]
Sorry I don't know why it is not working.

You can try to add the array directly to see if it is ok like this:
```javascript
this.$$('paper-datatable-api').data = [your collection];
```

If it is ok, probably there is an issue with puppetjs.

**Comment by atifwaqar** [comment]
ok, the code looks like this now (let me know if there is any mistake) : 
```
console.log(this.model.WebPublicationIdentifiers);
this.$$('paper-datatable-api').data = "{[{\"ObId\":\"BNR\",\"Host\":\"\",\"Regex$\":\"krogsveen\\.no/Kjoepe-bolig/.*?-(\\d{5}\\d*)\"},{\"ObId\":\"BuU\",\"Host\":\"\",\"Regex$\":\"asdf\"},{\"ObId\":\"Bul\",\"Host\":\"\",\"Regex$\":\"asdfasdf\"}]}";
console.log(this.$$('paper-datatable-api').data);
```
and this is what i see in console : 
![image](https://cloud.githubusercontent.com/assets/4388707/20896151/ae4972c6-bb1c-11e6-9f55-452b06bf59aa.png)

and its the same with this code aswell (difference in Json structure, additional `{` & `}` added) : 
```
this.$$('paper-datatable-api').data = "{[{\"ObId\":\"BNR\",\"Host\":\"\",\"Regex$\":\"krogsveen\\.no/Kjoepe-bolig/.*?-(\\d{5}\\d*)\"},{\"ObId\":\"BuU\",\"Host\":\"\",\"Regex$\":\"asdf\"},{\"ObId\":\"Bul\",\"Host\":\"\",\"Regex$\":\"asdfasdf\"}]";
```

**Comment by RoXuS** [comment]
Ok I see the problem, you set a string... Data is an Array.

Try this:
```javascript
this.$$('paper-datatable-api').data = JSON.parse("{[{\"ObId\":\"BNR\",\"Host\":\"\",\"Regex$\":\"krogsveen\\.no/Kjoepe-bolig/.*?-(\\d{5}\\d*)\"},{\"ObId\":\"BuU\",\"Host\":\"\",\"Regex$\":\"asdf\"},{\"ObId\":\"Bul\",\"Host\":\"\",\"Regex$\":\"asdfasdf\"}]");

// OR

this.$$('paper-datatable-api').data  = {[{\"ObId\":\"BNR\",\"Host\":\"\",\"Regex$\":\"krogsveen\\.no/Kjoepe-bolig/.*?-(\\d{5}\\d*)\"},{\"ObId\":\"BuU\",\"Host\":\"\",\"Regex$\":\"asdf\"},{\"ObId\":\"Bul\",\"Host\":\"\",\"Regex$\":\"asdfasdf\"}];
```

**Comment by RoXuS** [comment]
Probably it is the same issue with your `this.model.WebPublicationIdentifiers` it is a string so it does not work.

Try to set data with JSON.parse:
```javascript
this.$$('paper-datatable-api').data = JSON.parse(this.model.WebPublicationIdentifiers);
```

**Comment by atifwaqar** [comment]
Awesome. Your solution didn't fix the problem, but it helped me in getting this syntax : 
```
this.$$('paper-datatable-api').data = JSON.parse(JSON.stringify(this.model.WebPublicationIdentifiers));
```
I have no idea why this is happening, but this is at least working now. Do let me know if you figure out the reason of this issue.
Thanks a lot for your effort. :)

**Comment by RoXuS** [comment]
np

**Comment by atifwaqar** [comment]
Ok, Now I want to bind `this.model.WebPublicationIdentifiers`, so that when i use an editable column, and edit the data, it goes back to the Json. How do I do that?

**Comment by RoXuS** [comment]
`paper-datatable-api` isn't editable.

You have to do this manually like this example:
```html
<paper-datatable-api data="[[data]]">
  <paper-datatable-api-column header="Fruit" property="fruit">
    <template>
      <paper-input value="[[value]]"></paper-input>
      <paper-icon-button icon="edit" on-tap="_handleEdit"></paper-icon-button>
    </template>
  </paper-datatable-api-column>
</paper-datatable-api>
```
It is not complicated. You have to do `_handleEdit` function which send the new value to your server for example.

**Comment by atifwaqar** [comment]
Thank You for the help @RoXuS
