### ISSUE TITLE
Custom td styles

### ISSUE THREAD

**Issue by danielc103** [RoXuS/paper-datatable-api#18]
For some reason I can't set custom td styles.   

This isn't working.

```
<paper-datatable-api-column property="title" tdCustomStyle>
           <template>
                 <span>[[value]]</span>
           </template>
 </paper-datatable-api-column>
```

```
:host {
     --paper-datatable-api-tr-hover-background-color: var(--paper-blue-grey-50);
     --paper-datatable-api-custom-td: {
           color: red; 
     }
}
```

**Comment by RoXuS** [comment]
Hi @danielc103,

You have to user `td-custom-style` instead of `tdCustomStyle`.

Tell me know if you have other issues with that, it is "new" feature and you can set only one style...

**Comment by danielc103** [comment]
<s>Changing to td-custom-style in the tag did not work</s>

update - it works with ```td-custom-style```.  I was missing an end paren. Sorry.
