### ISSUE TITLE
Hidden column only hide header

### ISSUE THREAD

**Issue by haniiksan** [RoXuS/paper-datatable-api#19]
I have 3 column, "ID, Name, Email"
i want to hide column ID.

i try to hide column with property hidden on paper-datatable-api-column, but it's just hide header. Data still show.

**Comment by danielc103** [comment]
add the ```hideable``` property to ```paper-datatable-api-column```

**Comment by haniiksan** [comment]
Thanks, it's work.. :)

**Comment by RoXuS** [comment]
@haniiksan can I close this issue ?
