### ISSUE TITLE
Pagination: in-memory

### ISSUE THREAD

**Issue by foochris** [RoXuS/paper-datatable-api#2]
Is it possible to have in-memory pagination? I have an iron-ajax response that only returns all the data.

**Comment by RoXuS** [comment]
Hi @foochris,

For me the only good way for pagination is backend side.

If you want really use my element, you can do a mini custom-element to fake api.
I push an example in this commit: https://github.com/RoXuS/paper-datatable-api/commit/3b0d62183cdc9c703c9823b3682b8022c9bee086.

I have updated the demo too: https://roxus.github.io/paper-datatable-api/components/paper-datatable-api/.

Let me know if you have problems.

**Comment by foochris** [comment]
@RoXuS Thanks for the reply. Can you look at my question?

https://github.com/David-Mulder/paper-datatable/issues/83#issuecomment-234825647

I'm close to getting it work, but the datasource is undefined and I suspect I'm not setting a promise somewhere.

**Comment by foochris** [comment]
Thanks for you prompt response! Merci!
