### ISSUE TITLE
Sort event behavior?

### ISSUE THREAD

**Issue by danielc103** [RoXuS/paper-datatable-api#21]
On the 3rd press of the sort arrow I get weird behavior.  I'm assuming the behavior should be it toggles asc and desc every time. So the third press should have a direction of asc.  

My result on the third press is an empty ```event.detail.sort``` and a second fired event with and undefined on sort direction. 

![screen shot 2017-01-11 at 9 44 05 am](https://cloud.githubusercontent.com/assets/9359287/21852884/dba02e9e-d7e2-11e6-95e1-348ac69e996b.png)

**Comment by RoXuS** [comment]
hi @danielc103,

On the last version (0.2.1) ?

**Comment by danielc103** [comment]
just updated, I still get the same behavior.  I can now see why I get the empty object from ```deleteSortColumn```.

**Comment by RoXuS** [comment]
ok I see the bug, I fix it

**Comment by RoXuS** [comment]
Should be ok on master branch, could you test @danielc103 ?

**Comment by danielc103** [comment]
Yes, will test soon.

**Comment by danielc103** [comment]
@RoXuS I can't get the latest master from bower.  So far I've cleaned cached,  deleted bower_components and re installed, and forced update.

**Comment by RoXuS** [comment]
You can test on 0.2.2

**Comment by danielc103** [comment]
Thank you! That fixed the issue.  3rd click only fires once. 

<img width="320" alt="screen shot 2017-01-11 at 5 16 42 pm" src="https://cloud.githubusercontent.com/assets/9359287/21868664/de199f18-d821-11e6-9034-2a503623e72d.png">
