### ISSUE TITLE
Column header 

### ISSUE THREAD

**Issue by danielc103** [RoXuS/paper-datatable-api#22]
The column header when clicked is activated as an input.  Is there a property exposed to deactivate or allow it not to be in focus once clicked?

<img width="718" alt="screen shot 2017-01-11 at 6 51 28 pm" src="https://cloud.githubusercontent.com/assets/9359287/21871290/3f1cb16c-d82f-11e6-814d-9579353a7ab9.png">

**Comment by RoXuS** [comment]
Hi @danielc103,

Correct, it is fix in 0.2.3.

Sorry I recently make a refactor on header so there are some regressions.

I have added this test to avoid this issue (7b45c664e6a3cc6c21afcfbd71c6ad885dec4dd3).

Thx.

**Comment by danielc103** [comment]
Thanks again!  And no worries, I'm the one bothering you this week.
