### ISSUE TITLE
_dataChanged v0.2.4

### ISSUE THREAD

**Issue by danielc103** [RoXuS/paper-datatable-api#23]
the newest version released makes a small change to _dataChanged.  

This causes a small issue.  For example, if I have only one row in the table and I am deleting that last row, I will be passing an empty data array to the ```_dataChanged``` function.  That if statement will be evaluated to false and the last row will not be removed with the ```_removeRows``` call.

**Comment by RoXuS** [comment]
Hi @danielc103,

Yes thx for the bug, I have commited a fix (7be622ee3bc3d83cf2e2b939bba1aa1dfe0ea083).
Test with 0.2.5.

**Comment by danielc103** [comment]
super fast response!
