### ISSUE TITLE
Single selection needed

### ISSUE THREAD

**Issue by devmikko** [RoXuS/paper-datatable-api#24]
Hi, can we have the ability to select only one row at a time?

**Comment by RoXuS** [comment]
Hi @devmikko,

You want select one row with the checkbox or display only one row at a time ?

**Comment by devmikko** [comment]
Just select one row not multi select.
Just like paper-datatable of David when 'multi-select' is false

**Comment by RoXuS** [comment]
Ohh yes, there is a `allowTheSelectionOfAllTheElements` property (default: true), you have to set it to false.

It is describe in the Doc API : https://roxus.github.io/paper-datatable-api/components/paper-datatable-api/#paper-datatable-api.

**Comment by RoXuS** [comment]
It's probably not the best property name ...

**Comment by devmikko** [comment]
Oh, I see, thank you very much!

**Comment by Pankraz76** [comment]
Does not work for me. The property does not change anyhting at all.

**Comment by Pankraz76** [comment]
@RoXuS although the prop only changed "the paper-checkbox in the header which allow to select all rows is hidden" does not mean only one row can be selected like mentioned above.

**Comment by Ewanuk** [comment]
Confirmed, I set the property to false and I can still select multiple rows.
