### ISSUE TITLE
Empty rows when using dom-repeat

### ISSUE THREAD

**Issue by H3dz** [RoXuS/paper-datatable-api#25]
Since 0.2.7 the rows are empty when the element is inside a dom-repeat template.

I tested and it worked fine with 0.2.6

Example:

```
<template is="dom-repeat" items="[[items]]">
  <paper-datatable-api data="[[item.values]]">...</paper-datatable-api>
</template>
```

**Comment by RoXuS** [comment]
@H3dz I take a look now, thx

**Comment by RoXuS** [comment]
@H3dz I can't reproduce the bug on `Advanced demo` and `Simple demo` (from demo folder).
Do you have a more complexe examples ?

**Comment by RoXuS** [comment]
You can see the following commit aad634b942ba62dd6f8f3317987f4d213e274b6d on [this branch](https://github.com/RoXuS/paper-datatable-api/compare/paperDatatableApiWithDomRepeat).

**Comment by H3dz** [comment]
It's when a different set of data is repeated. In your test the same data is used.

data.json looks like this:

```
[
  [
    {
      "color": "yellow",
      "fruit": "banana",
      "weight": {
        "kg": "0.12gr",
        "gr": "120gr"
      },
      "hiddenColumn": 1
    }
  ],
  [
    {
      "color": "orange",
      "fruit": "Orange",
      "weight": {
        "kg": "3.12gr",
        "gr": "120gr"
      },
      "hiddenColumn": 1
    }
  ]
]

```

And the code like:

```
<template is="dom-repeat" items="[[data]]">
          <paper-card heading="Simple demo">
            <div class="card-content">
              <paper-datatable-api data="[[item]]">
```

**Comment by RoXuS** [comment]
Ohhh, I see. Can you test on master branch ? The last commit (8533f585bf3d11466d602789fa7a0158e9810c18) should fix the issue.

**Comment by H3dz** [comment]
Yes that fixed it, thanks.
