### ISSUE TITLE
Change the default value of allowTheSelectionOfAllTheElements to false

### ISSUE THREAD

**Issue by benjaminrancourt** [RoXuS/paper-datatable-api#28]
According to http://stackoverflow.com/a/31183861, we can't set the allow-the-selection-of-all-the-elements property to false as his type is Boolean and his default value is true. Is it possible for you to change the default value of this property?

```
 <!-- Not working -->
<paper-datatable-api
	 allow-the-selection-of-all-the-elements="false">
	 ...
</paper-datatable-api>
```

**Comment by RoXuS** [comment]
Hello @ranb2002, thx for using this component.

Hum, it is possible but you can set attribute to false if you use Polymer in the parent component.

For example :
```
<paper-datatable-api
	 allow-the-selection-of-all-the-elements="[[myValue]]">
	 ...
</paper-datatable-api>
```
```javascript
Polymer({
...
properties: {
  myValue: {
    type: Boolean,
    value: false,
  },
},
});
```

It's not enough for you ?

**Comment by benjaminrancourt** [comment]
Hi,

Thank you very much for your quick reply, the proposed solution works.
A proper way if you want to conserve the default value to true is to set his type to Object, so we could set the property with 'allow-the-selection-of-all-the-elements="false"'. It's also working.

Thank you for your component :)
