### ISSUE TITLE
Custom column sorting

### ISSUE THREAD

**Issue by foochris** [RoXuS/paper-datatable-api#3]
Is it possible to have custom column sorting similar to https://github.com/David-Mulder/paper-datatable?

![screen shot 2016-07-25 at 11 46 35 am](https://cloud.githubusercontent.com/assets/1527289/17107503/81bdec1e-525d-11e6-947e-b18261d38572.png)

```
<paper-datatable-column header="risk rating" property="rating" type="String" sortable class="rating_header" sort="customObjectSorter">

```

**Comment by RoXuS** [comment]
I think it is already done.

You can listen a sort event which contains:

```
Object {sort: Object, column: paper-datatable-api-column}

{
  column: "The column element",
  sort: {
    direction:"asc|desc"
    property: "value"
  }
}
```

So if you handle this event you can easily do the job:

``` javascript
      _handleSort: function(event) {
        var sortPropertyName = event.detail.sort.property;
        var direction = event.detail.sort.direction;
        if (sortPropertyName === 'headername') {
          // Do a specific sorting
        } else if (...) {
          // Do an other specific sorting
        } else {
          // Do the default sorting
        }
      }
```

Oh and you have access to the column element so you can add an attribute like this `<paper-datatable-column header="risk rating" property="rating" type="String" sortable class="rating_header" sort-name="myspecificsort>` and use it in `_handleSort`:

``` javascript
      _handleSort: function(event) {
        var column = event.detail.column;
        var sortPropertyName = event.detail.sort.property;
        var direction = event.detail.sort.direction;
        if (column.sortName === 'myspecificsort') {
          // Do a specific sorting
        } else if (...) {
          // Do an other specific sorting
        } else {
          // Do the default sorting
        }
      }
```

It is ok for you ?

**Comment by foochris** [comment]
Yes, this is great! Thanks for your very prompt response.
