### ISSUE TITLE
Is this component compatible with polymer 2.0?

### ISSUE THREAD

**Issue by bmodeprogrammer** [RoXuS/paper-datatable-api#32]
I'm doing some prototypes with polymer 2.0, and tried to use this component and crashed the application.

> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': "undefined" is not a valid custom element name
    at Function.window.Polymer._polymerFn (http://127.0.0.1:8081/bower_components/polymer/lib/legacy/polymer-fn.html:41:22)

**Comment by RoXuS** [comment]
Hello @schmeisk,

I work on this, it should be available quiclky.

**Comment by bmodeprogrammer** [comment]
Thank you @RoXuS 
Continue doing your awesome job.

**Comment by RoXuS** [comment]
Hello @schmeisk,

First draft on polymer 2.0 rc3 -> https://github.com/RoXuS/paper-datatable-api/tree/2.0-preview .

All tests are ok (https://travis-ci.org/RoXuS/paper-datatable-api/builds/213786052) but the filter on date columns doesn't work because vaadin component is not in polymer 2.0.0...

**Comment by bmodeprogrammer** [comment]
Thank you, I will test it.
