### ISSUE TITLE
How To Get Selected Rows

### ISSUE THREAD

**Issue by MWalid** [RoXuS/paper-datatable-api#33]
Hello,

Here is my code:

```

    <paper-datatable-api data="[[stages]]" selectable>
        <paper-datatable-api-column draggable-column header="#" property="id">
          <template>
            <span>{{value}}</span>
          </template>
        </paper-datatable-api-column>
       ... 
       <!-- REST OF COLUMNS ARE HERE -->
      </paper-datatable-api>
```

I really can't figure it out how to get selected rows from the above snippet,

Thank you,

**Comment by RoXuS** [comment]
Hello @MWalid,

Like in this demo https://github.com/RoXuS/paper-datatable-api/blob/master/demo/advanced-demo.html#L85.

You have an exposed property named selectedRows so you have to add this attribute in your `paper-datatable-api`.

```HTML
    <paper-datatable-api data="[[stages]]" selectable selected-rows={{selectedRows}}>
```

**Comment by MWalid** [comment]
Thank you RoXuS 👍

**Comment by RoXuS** [comment]
@MWalid can I close this issue ?

**Comment by RoXuS** [comment]
@MWalid, I close the issue, if you have other questions don't hesitate to reopen it
