### ISSUE TITLE
Custom template for editing cell values

### ISSUE THREAD

**Issue by simonealessandrelli** [RoXuS/paper-datatable-api#34]
Have you planned this feature (already present in old David mulder library)?

**Comment by RoXuS** [comment]
Hello @simonealessandrelli,

Have you an example ?
I provide a demo for the edit case => https://github.com/RoXuS/paper-datatable-api/blob/master/demo/edit-demo.html

**Comment by RoXuS** [comment]
I close this issue, if you have any other questions, don't hesitate to reopen it.
