### ISSUE TITLE
Missing iron-icons dependency

### ISSUE THREAD

**Issue by H3dz** [RoXuS/paper-datatable-api#35]
PolymerElements/iron-icons should be in the dependencies of the bower.json file.

Ideally, I think it would be better if a custom set of icons was created to avoid loading all the icons for no reason.
See:  https://poly-icon.appspot.com/

Also, maybe a lite version could be created where other dependencies like vaadin-date-picker/vaadin-date-picker-light.html are excluded.

**Comment by RoXuS** [comment]
@H3dz Good idea, could you test on this branch https://github.com/RoXuS/paper-datatable-api/commits/2.0-preview-custom-icons ?

**Comment by H3dz** [comment]
Works well, except that the ones in div#footerWrapper were not updated.

**Comment by RoXuS** [comment]
Ok I have added, it should be ok.

If you are ok, I will merge this on [2.0-preview]( https://github.com/RoXuS/paper-datatable-api/tree/2.0-preview) branch.

**Comment by H3dz** [comment]
Looks good!
