### ISSUE TITLE
Sort event undefined values

### ISSUE THREAD

**Issue by H3dz** [RoXuS/paper-datatable-api#38]
Looks like there's a bug with the sort logic.

When sorting from desc to asc the sort event will first fire undefined values (looks like deleteSortColumn is called).

To reproduce, click 3 times on the Fruits column of the advanced demo,
you should get this error:
GET https://roxus.github.io/paper-datatable-api/components/paper-datatable-api/demo/data/data-page=0&size=2&sort=undefined,undefined.json 404 (Not Found)

**Comment by RoXuS** [comment]
Hello @H3dz, it is the correct behavior, the third time back to the normal case, so the properties of the sort are undefined.

It is a problem for you ?

**Comment by H3dz** [comment]
Hi @RoXuS, yes, I think it should toggle between asc and desc.

I never saw a table with an in between behavior and I think it's confusing for the user.
Also, the arrow icon makes it seems like the column is sorted.
I looked at other JS tables and they are all sorted between asc and desc.

The spec for material design state that:

> If the user clicks on a column that is already sorted, reverse the sort order and rotate the sort icon.
https://material.io/guidelines/components/data-tables.html#data-tables-interaction

**Comment by H3dz** [comment]
Looks like other grids have the same behavior.

Closing this as it is an intended behavior.
