### ISSUE TITLE
2.0 Update custom property syntax

### ISSUE THREAD

**Issue by H3dz** [RoXuS/paper-datatable-api#39]
The custom property syntax was not updated in paper-datatable-api-shared-styles.html

Example:
background-color: var(--paper-datatable-api-tr-selected-background, --paper-grey-100);
should be
background-color: var(--paper-datatable-api-tr-selected-background, var(--paper-grey-100));

See https://www.polymer-project.org/2.0/docs/upgrade

> Update custom property syntax
> 
> When applying custom properties, Polymer 1.x accepted this incorrect syntax for specifying a default value to a var() function:
> 
> Before
> color: var(--special-color,--default-color);
> By specification, the default (or fallback) is a CSS value, not a custom property name. To use a custom property as a default, add a nested var() function.
> 
> After
> color: var(--special-color, var(--default-color));

**Comment by RoXuS** [comment]
Thx !

**Comment by H3dz** [comment]
```
      paper-checkbox {
        --paper-checkbox-label-spacing: 0;
        --paper-checkbox-checked-color: var(--paper-datatable-api-checked-checkbox-color, --primary-color);
        --paper-checkbox-unchecked-color: var(--paper-datatable-api-unchecked-checkbox-color, --primary-text-color);
      }
```

Also needs to be updated.
