### ISSUE TITLE
2.0 - paper-datatable-api-footer no longer works with polymer 2.0.0-rc.7

### ISSUE THREAD

**Issue by H3dz** [RoXuS/paper-datatable-api#41]
paper-datatable-api-footer.js wasn't migrated to version 2 and no longer works with polymer 2.0.0-rc.7

**Comment by RoXuS** [comment]
Thx @H3dz, I fix that quickly

**Comment by RoXuS** [comment]
@H3dz, should be ok !

**Comment by H3dz** [comment]
@RoXuS works, thanks!
