### ISSUE TITLE
Make table responsive on mobile phone screen

### ISSUE THREAD

**Issue by chavu** [RoXuS/paper-datatable-api#42]
How do I make the table with many columns responsive on mobile phone screen?

**Comment by RoXuS** [comment]
Hi @chavu,

For mobile phone I preconize to use a list view with `paper-item` (use `three-line` option).
I you look the material design guide there is nothing about mobile view on table section -> https://material.io/guidelines/components/data-tables.html.

Nevertheless, the table works on mobile, you will have a vertical scroll, but it is usable no ?
