### ISSUE TITLE
How can we use more than one property

### ISSUE THREAD

**Issue by bliveinhack** [RoXuS/paper-datatable-api#43]
Hey,

i want to make one column based on some computation. like the value is `fname , lname`. so how can we use two properties together?

**Comment by govis** [comment]
I have the same question. Having to set <code>property</code> and <code>otherProperties</code> on the <code>paper-datatable-api-column</code> doesn't feel right. Would it not make more sense to pass the whole row object to the template and have it pick the property, use <code>dom-if</code> templates and helper functions that pick properties based on various conditions etc. Thank you for carrying on the torch of data-table through Polymer 2.0!

**Comment by RoXuS** [comment]
Hello @bliveinhack,

Yes you have to use `otherProperties` to add one or more attribute to the column.

@govis, for now I have no solution for this, you can add a depth to your object with the entire row data in a property that you set in `otherProperties` ?

I close this issue, don't hesitate to reopen it if you have any questions.

**Comment by Damianruizz** [comment]
I am using `otherProperties` to show multiple properties in a column, but I do not know how to show them, with only one property shown with `value,` here I do not know how to show the other properties
