### ISSUE TITLE
Access whole row data from column

### ISSUE THREAD

**Issue by papusa** [RoXuS/paper-datatable-api#44]
Hi,

We are trying to move from paper-datatable to paper-datatable-api. 
As I understand to access some other properties of a row data I have to define it in 'other-properties' attribute.
`              <paper-datatable-api-column header="Fruit" property="fruit" other-properties='["color"]'>
                <template>
                  <span>[[value]], color: [[otherValues.color]]</span>
                </template>
              </paper-datatable-api-column>` 

This is a bit inconvenient. Is there a possibility to access entire row data?
Like it is in paper-datatable:
`                        <paper-datatable-column header="No" property="No" type="Number" sortable>
                            <template>
                                <span class="id-cell" inactive$="[[!**item**.IsActive]]">[[value]]</span>
                            </template>
                        </paper-datatable-column>`

Thank you

**Comment by RoXuS** [comment]
Hi @papusa,

You can add a depth on each objects with your entire row data, else there is no way to do that with my component, sorry ...
