### ISSUE TITLE
Selecting/Deselecting rows from code

### ISSUE THREAD

**Issue by govis** [RoXuS/paper-datatable-api#48]
I am trying to deselect individual rows upon submitting changes to the back-end. Current implementation does not appear to be handling <code>selectedRows splice</code>, so I was wondering if this is something that you are planning to support in the future?

**Comment by sntg-p** [comment]
I am trying to do something similar. I want to clear the rows selection programmatically but it seems that there is currently no way to do that, and I couldn't add the functionality myself as I am still a bit of a noob with JavaScript.

**Comment by bstmedia** [comment]
+1

**Comment by Pankraz76** [comment]
+1
pretty annoying that there is no solution for this case (Deselecting rows). Doesn´t feels that edgy for me, so I don´t understand why this is not already implemented...

**Comment by bdekk** [comment]
You can pass in the selectedRows and change that object.
`<paper-datatable-api selected-rows="{{selectedRows}}">`

Somewhere in your code:
`this.set('selectedRows', []);`

**Comment by govis** [comment]
Ok, I'll give it a try. Thanks

**Comment by bstmedia** [comment]
This works great or individual rows. But it keeps the "select all" box checked in my case.

**Comment by bdekk** [comment]
@bstmedia I have the same problem. It seems that there is no trigger to deselect / select the select all checkbox on changing the selection of rows (no rows selected or all rows selected).
