### ISSUE TITLE
Loading indicator while the table data changes

### ISSUE THREAD

**Issue by roothema** [RoXuS/paper-datatable-api#49]
Hi,

is it possible to add a loading spinner to the table ui? My use case is when the user clicks on the next page button then this event triggers an ajax call to the backend to gather data and fill the table with it. Currently the behaviour is that when the new data arrives then the whole table reloaded. 

```
_handleResponse(event) {
        this._response = event.detail.response.content;
        this.totalElements = event.detail.response.totalElements;
        this.totalPages = event.detail.response.totalPages;

        this.data = this._response.slice(0, this.size);
}
```

It would be nice to have a smoother loading animation instead of the current raw reload.

**Comment by RoXuS** [comment]
Hi @roothema,

We do the same thing and we use the `loading` property from the `iron-ajax` Component to display a loading animation (for example on the top of the card where the paper-datatable-api is used).

Currently, we haven't animation inside the component.

**Comment by roothema** [comment]
@RoXuS, thanks for the info!
