### ISSUE TITLE
Column header formatting

### ISSUE THREAD

**Issue by foochris** [RoXuS/paper-datatable-api#5]
Is it it possible to apply a style to the column header?

https://github.com/David-Mulder/paper-datatable/blob/master/paper-datatable-column.html#L160

**Comment by RoXuS** [comment]
Yes here => https://roxus.github.io/paper-datatable-api/components/paper-datatable-api/#paper-datatable-api.

You have some mixins for the header: `--paper-datatable-api-header` or `--paper-datatable-api-header-sorted`.

**Comment by foochris** [comment]
Thanks. I saw that after re-reading the docs!
