### ISSUE TITLE
selectedRows keeps its content even after changing data set

### ISSUE THREAD

**Issue by sntg-p** [RoXuS/paper-datatable-api#50]
I managed to clear the checked rows by refreshing the data set but the selectedRows property mantains it's contents. I think a good fix would be adding `this.set('selectedRows', []);` inside the `_dataChanged()` function.

**Comment by RoXuS** [comment]
Hi @SantiagoLP98, I keep `selectedRows` on `_dataChanged()` because when the page change I want to keep the selected rows !

You have to manually handle this case.

If you have another question you can reopen this issue !
