### ISSUE TITLE
Change datatable view in runtime

### ISSUE THREAD

**Issue by sudipta1411** [RoXuS/paper-datatable-api#52]
In the advanced-demo example, can one change the array "dataFromApi" and expect the view changed?
I want to sort the array on some key, will that be reflected on the table?

**Comment by RoXuS** [comment]
Hello @sudipta1411, yeah it is the purpose of this component, all data change from the API will be reflected on the table, it is not the case ?

**Comment by sudipta1411** [comment]
Yeah, sorry I had done something wrong with the data. It is working as expected

**Comment by RoXuS** [comment]
Ok ^^ I close it, thx
