### ISSUE TITLE
rows are not selected

### ISSUE THREAD

**Issue by aaroncadillac** [RoXuS/paper-datatable-api#55]
I added the selectable property and it does not work, you see the boxes to select, but they do not have functionality, the selected rows attribute is empty.

Does anyone know why this happens?

My code
  ```
<paper-datatable-api 
      selectable
      data="[[incidents]]"
      selected-rows={{selectedIncident}
      selectable-data-key="id_incident">
      <paper-datatable-api-column header="ID" property="id_incident" sortable>
        <template>
          <span>{{value}}</span>
        </template>
      </paper-datatable-api-column>
      ...more columns
    </paper-datatable-api>
```

Note: all right with the data and the properties, that's not the problem

**Comment by bdekk** [comment]
@aaroncadillac  You do not close your selected-rows property properly. You only have one closing curly-brace. {{selectedIncident}

**Comment by RoXuS** [comment]
thx @bdekk, @aaroncadillac you can add `on-selection-changed="_selectionChanged"` to check change.

**Comment by RoXuS** [comment]
I close this issue, don't hesitate to reopen it if you still have the problem.
