### ISSUE TITLE
is it possible to use  dom-repeat to change the header properties dynamically ?

### ISSUE THREAD

**Issue by amandaSalander** [RoXuS/paper-datatable-api#58]
I would like to dynamically change the header depending of the properites present in the objects in the _forages array, is there a way to achieve it ?

```html
 <paper-datatable-api data="[[_forages]]">
                 <template is="dom-repeat" items=[[_currentProperties]] as="property">
                     <paper-datatable-api-column draggable-column header="[[property]]" property="[[property]]">
                          <template>
                              <span>{{value}}</span>
                          </template>
                      </paper-datatable-api-column>
                  </template>  
</paper-datatable-api>
```

![image](https://user-images.githubusercontent.com/24660070/36345749-f76ec820-1430-11e8-915b-cc500d266f63.png)

**Comment by RoXuS** [comment]
hello @amandaSalander, it should work, you have an example here -> https://github.com/RoXuS/paper-datatable-api/blob/master/demo/dynamic-headers-demo.html

**Comment by amandaSalander** [comment]
it's working now I had a problem with _forages.
thank you  @RoXuS
