### ISSUE TITLE
pivot table support?

### ISSUE THREAD

**Issue by kpx-dev** [RoXuS/paper-datatable-api#7]
Hi @RoXuS 

Great project! I'm planning on using it for my report project. Do you think if it's possible to add in support for a pivot table?

```
Ex:
Date       User1           User2          User3
01/01      xyz               blah             blah
01/02     zzzz              zzzz            zzzz
```

The idea here is we would be able to set dynamic columns and dynamic rows based on the data set.

**Comment by RoXuS** [comment]
hi @kienpham2000,

You made some tests ?

For dynamic rows no problem but perhaps for dynamic columns there may be a problem.
I have to do some test then I will back to you with more info, probably tomorrow.

Thx.

**Comment by kpx-dev** [comment]
@RoXuS not yet, I'm trying to implement this package into my project now and trying to see if it can do pivot table now.

**Comment by RoXuS** [comment]
I close this issue, don't hesitate to open it again if you have a more questions!
