### ISSUE TITLE
Not really an issue but more of a question

### ISSUE THREAD

**Issue by esd100** [RoXuS/paper-datatable-api#9]
It's too bad that the paper-datatable by Mulder is no longer being maintained.

Do you know if it is possible to put an image in one of the data-column cells?

I want to convert a URI stored in the database into an image and then put the image in the cell.

P.S. - I opened the issue because I don't know how to contact you directly.

**Comment by RoXuS** [comment]
Hello @esd100,

Yes you can, for example if you have a simple data.json like this :

``` json
[
  {
    "imageUrl": "http://..."
  }
]
```

You can display the image in the cell like this:

``` html
        <iron-ajax auto url="data/data.json" last-response="{{data}}"></iron-ajax>

        <paper-datatable-api data="[[data]]">
          <paper-datatable-api-column header="Image" property="imageUrl">
            <template>
              <img src$="[[value]]" />
            </template>
          </paper-datatable-api-column>
        </paper-datatable-api>
```

**Comment by RoXuS** [comment]
@esd100, can I close this issue or you want more info ?

**Comment by esd100** [comment]
Hey RoXus, yes, thank you very much for your help! I was able to accomplish this.

On another topic, I wanted to know if styling with alternating rows is possible?

**Comment by RoXuS** [comment]
@esd100 now it is possible see commit 67bd764e4862a4a567160b0753cfaf4b7df852bb from @H3dz.
